### ISSUE TITLE
website 404s

### ISSUE THREAD

**Issue by jefftriplett** [natbat/scicomm-calendar#25]
I saw your tweet and I dropped by to check out your GitHub Action workflow actions. I tried to click on https://natbat.github.io/scicomm-calendar/ to check out what you were doing and it looks like it's a 404. Since you switch your branch over to `main` maybe GitHub doesn't know to build the website from the new branch? 

(Apologies if this is by design.)

**Comment by natbat** [comment]
Oh drat, thanks Jeff!

**Comment by natbat** [comment]
You were right Jeff, there is a setting for Github pages in the settings page, it hadn’t updated the branch name. Fixed now! Thank you https://natbat.github.io/scicomm-calendar/
